---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: silverbullet
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      silverbullet:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            runAsNonRoot: true
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 65542
        containers:
          app:
            image:
              repository: ghcr.io/silverbulletmd/silverbullet
              tag: v2
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 12m
                memory: 128M
              limits:
                memory: 512M
    service:
      app:
        controller: silverbullet
        ports:
          http:
            port: 3000
    ingress:
      app:
        className: "internal-nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-int.${DOMAIN}
        hosts:
          - host: silverbullet.${DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      data:
        existingClaim: silverbullet-data
        advancedMounts:
          silverbullet:
            app:
              - path: /space
      nas:
        type: nfs
        server: asc.internal
        path: /mnt/tank/apps/silverbullet
        advancedMounts:
          silverbullet:
            app:
              - path: /data/nas
