---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
spec:
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      plex:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 44
              - 109
              - 65542  # gladius:external-services
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/plex
              tag: 1.42.1.10060
            env:
              PLEX_ADVERTISE_URL: https://10.1.1.136:32400,https://plex.${DOMAIN}:443
              PLEX_NO_AUTH_NETWORKS: 10.244.0.0/16
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 100m
                gpu.intel.com/i915: 1
                memory: 9248M
              limits:
                gpu.intel.com/i915: 1
                memory: 9248M
    service:
      app:
        controller: plex
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 10.1.1.136
        ports:
          http:
            port: 32400
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-ext.${DOMAIN}
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        className: "external-nginx"
        hosts:
          - host: plex.${DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: plex-config
        advancedMounts:
          plex:
            app:
              - path: /config
      plex-cache:
        existingClaim: plex-cache
        advancedMounts:
          plex:
            app:
              - path: /config/Library/Application Support/Plex Media Server/Cache
      logs:
        type: emptyDir
        advancedMounts:
          plex:
            app:
              - path: /config/Library/Application Support/Plex Media Server/Logs
      nfs-nas-media:
        type: nfs
        server: asc.internal
        path: /mnt/tank/media
        advancedMounts:
          plex:
            app:
              - path: /data/nas-media
      transcode:
        type: emptyDir
        advancedMounts:
          plex:
            app:
              - path: /transcode
