---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-iot",
                "namespace": "network",
                "ips": ["10.1.30.151/24"],
                "mac": "3e:59:e4:f7:43:08"
              }]
        containers:
          app:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2025.4.4
            envFrom:
              - secretRef:
                  name: home-assistant-secret
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 47m
                memory: 2Gi
              limits:
                memory: 2Gi
    service:
      app:
        controller: home-assistant
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 10.1.1.144
        ports:
          http:
            port: 8123
    ingress:
      app:
        className: "external-nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-ext.${DOMAIN}
        hosts:
          - host: hass.${DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: home-assistant-config
        advancedMounts:
          home-assistant:
            app:
              - path: /config
      deploy-key:
        type: secret
        name: home-assistant-secret
        defaultMode: 256
        globalMounts:
          - path: /root/.ssh/id_rsa
            subPath: GH_DEPLOY_KEY
