---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: soft-serve
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      soft-serve:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            image:
              repository: "ghcr.io/charmbracelet/soft-serve"
              tag: v0.8.5@sha256:0a2c9d5047003cc1ad65a49d98fee12d04efcfe82950e22c35fedd3636ce5558
            env:
              TZ: "${CONFIG_TZ}"
              SOFT_SERVE_NAME: "Nebular Grid"
              SOFT_SERVE_LOG_FORMAT: "json"
              SOFT_SERVE_SSH_LISTEN_ADDR: ":23231"
              SOFT_SERVE_SSH_PUBLIC_URL: "ssh://git.${DOMAIN}:22"
              SOFT_SERVE_GIT_LISTEN_ADDR: ":9418"
              SOFT_SERVE_HTTP_LISTEN_ADDR: ":23232"
              SOFT_SERVE_HTTP_PUBLIC_URL: "https://git.${DOMAIN}"
              SOFT_SERVE_STATS_LISTEN_ADDR: ":23233"
              SOFT_SERVE_LFS_ENABLED: "true"
              SOFT_SERVE_LFS_SSH_ENABLED: "true"
              SOFT_SERVE_DB_DRIVER: "sqlite"
              SOFT_SERVE_INITIAL_ADMIN_KEYS:
                valueFrom:
                  secretKeyRef:
                    name: soft-serve-secret
                    key: ADMIN_KEYS
            resources:
              requests:
                cpu: "10m"
                memory: "128Mi"
              limits:
                cpu: "3000m"
                memory: "1Gi"
            securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
    service:
      app:
        controller: soft-serve
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "git.${DOMAIN}"
          io.cilium/lb-ipam-ips: 10.1.1.140
        ports:
          http:
            port: 443
            targetPort: 23232
          ssh:
            enabled: true
            targetPort: 23231
            port: 22
            protocol: TCP
          git:
            enabled: true
            port: 9418
            protocol: TCP
    persistence:
      data:
        existingClaim: soft-serve-data
        advancedMounts:
          soft-serve:
            app:
              - path: /soft-serve
