---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matter
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      matter:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-iot",
                "namespace": "network",
                "ips": ["10.1.30.152/24"],
                "mac": "aa:8c:ae:86:6e:8a"
              }]
          securityContext:
            runAsUser: 0  # Must be run as root user
            runAsGroup: 0
            runAsNonRoot: false  # Must be run as root user
            fsGroup: 0
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            image:
              repository: ghcr.io/home-assistant-libs/python-matter-server
              tag: 8.1.0
              pullPolicy: IfNotPresent
            args:
              - --storage-path=/data
              - --primary-interface=net1
              - --log-level=debug
              - --log-level-sdk=info
            env:
              TZ: "${TIMEZONE}"
              MATTER_SERVER__INSTANCE_NAME: Matter-Server
              MATTER_SERVER__PORT: &port 5580
              MATTER_SERVER__APPLICATION_URL: "matter.${DOMAIN}"
              MATTER_SERVER__LOG_LEVEL: info
              MATTER_SERVER__VENDOR_ID: 4939
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                memory: "120M"
                cpu: "100m"
              limits:
                memory: "500M"
                cpu: "1000m"
    defaultPodOptions:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
    service:
      app:
        controller: matter
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: 10.1.1.138
        ports:
          api:
            enabled: true
            primary: true
            protocol: TCP
            port: *port
          mdns-tcp:
            enabled: true
            port: 5353
            protocol: TCP
            targetPort: 5353
          mdns-udp:
            enabled: true
            port: 5353
            protocol: UDP
            targetPort: 5353
    persistence:
      data:
        existingClaim: matter-config
        globalMounts:
          - path: /data
