---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
spec:
  provider:
    onepassword:
      # connectHost: http://onepassword-connect.${DOMAIN}
      connectHost: http://10.1.1.12:7780
      vaults:
        NebularGrid: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token
            key: token
            namespace: security
