---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zigbee2mqtt-secret
    creationPolicy: Owner
  data:
    - secretKey: zigbee_pan_id
      remoteRef:
        key: Zigbee2MQTT
        property: pan id
    - secretKey: zigbee_ext_pan_id
      remoteRef:
        key: Zigbee2MQTT
        property: ext pan id
