---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      qbittorrent:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 65542
        initContainers:
          dnsdist:
            image:
              repository: docker.io/powerdns/dnsdist-19
              tag: 1.9.10@sha256:7495affd85c450050eb2fce1cb99964cb439482ffada22e9d312a761b6bf138d
            restartPolicy: Always
          gluetun:
            dependsOn:
              - dnsdist
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.0@sha256:2b42bfa046757145a5155acece417b65b4443c8033fb88661a8e9dcf7fda5a00
            restartPolicy: Always
            env:
              DOT: "off"
              DNS_ADDRESS: 127.0.0.2
              VPN_SERVICE_PROVIDER: nordvpn
              VPN_TYPE: wireguard
              SERVER_COUNTRIES: Germany
              FIREWALL_INPUT_PORTS: "8080,9999"
              HEALTH_SERVER_ADDRESS: ":9999"
              FIREWALL_OUTBOUND_SUBNETS: 10.96.0.0/12,10.244.0.0/16  # Allow access to k8s subnets
            envFrom:
              - secretRef:
                  name: qbittorrent-vpn-secret
            lifecycle:
              postStart:
                exec:
                  command: ["/bin/sh", "-c", "(ip rule del table 51820; ip -6 rule
                      del table 51820) || true"]
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /check
                    port: 9999
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /check
                    port: 9999
                  initialDelaySeconds: 10
            securityContext:
              capabilities:
                add: [NET_ADMIN]
                allowPrivilegeEscalation: false
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.0
            env:
              QBT_WEBUI_PORT: &port 8080
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 5m
                memory: 1024Mi
              limits:
                memory: 6144Mi
            securityContext:
              runAsUser: 2000
              runAsGroup: 2000
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
          port-forward:
            image:
              repository: ghcr.io/bjw-s-labs/gluetun-qb-port-sync
              tag: 0.0.4@sha256:838ba41b3c736b23ae30f7e79a2610173f389a5ac6fb2b3e9c7bd482b9353c18
            env:
              GLUETUN_CONTROL_SERVER_HOST: localhost
              GLUETUN_CONTROL_SERVER_PORT: 8000
              QBITTORRENT_HOST: localhost
              QBITTORRENT_WEBUI_PORT: &port 8080
              CRON_ENABLED: true
              CRON_SCHEDULE: "*/5 * * * *"
              LOG_TIMESTAMP: false
            securityContext:
              runAsUser: 568
              runAsGroup: 568
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
    service:
      app:
        controller: qbittorrent
        ports:
          http:
            port: *port
    ingress:
      app:
        className: "internal-nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-int.${DOMAIN}
        hosts:
          - host: qbittorrent.${DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: qbittorrent-config
        advancedMounts:
          qbittorrent:
            app:
              - path: /config
      empty-config:
        type: emptyDir
        advancedMounts:
          qbittorrent:
            port-forward:
              - path: /config
      media:
        type: nfs
        server: asc.internal
        path: /mnt/tank/media
        globalMounts:
          - path: /data/nas-media
      temp:
        type: emptyDir
        advancedMounts:
          qbittorrent:
            app:
              - path: /tmp
      dnsdist:
        type: configMap
        name: qbittorrent-configmap
        advancedMounts:
          qbittorrent:
            dnsdist:
              - path: /etc/dnsdist/dnsdist.conf
                subPath: dnsdist.conf
                readOnly: true
