---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    configMaps:
      config:
        data:
          mosquitto.conf: |
            allow_anonymous true
            autosave_interval 60
            connection_messages false
            listener 1883
            per_listener_settings false
            persistence true
            persistence_location /config
    controllers:
      mosquitto:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.0.22
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 5m
                memory: 10M
              limits:
                memory: 10M
    service:
      app:
        controller: mosquitto
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "mqtt.${DOMAIN}"
          io.cilium/lb-ipam-ips: 10.1.1.135
        ports:
          mqtt:
            enabled: true
            port: 1883
    persistence:
      config:
        existingClaim: "mosquitto-cache"
      config-file:
        type: configMap
        identifier: config
        advancedMounts:
          mosquitto:
            app:
              - path: /mosquitto/config/mosquitto.conf
                subPath: mosquitto.conf
